// Preliminary AI-generated Bystander video (Kling VIDEO 3.0, scenario 95–185 s), half-equirectangular 180°, mono.
// The video is stored encrypted: a random content key encrypts the video (AES-256-GCM), and that key is itself
// encrypted with the key derived from the study password (PBKDF2-SHA-256, the same salt and rounds as the other
// protected sessions). Nothing readable sits on the server.
import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.min.js';

const SALT = 'Ermju/gB3rbmZtE/7vFo2g==', ITER = 310000;
const BASE = '/projects/scalable-immersion-videos/generated-bystander-assets/';
const VIDEO_FILE = 'prelim-95-185.mp4.enc', KEY_FILE = 'content-key.enc';
const KEEP = 'si-world-access';
const DELIVERY = window.SI_DELIVERY === 'headset' ? 'headset' : 'screen';

const $ = (id) => document.getElementById(id);
const form = $('gate'), pw = $('pw'), btn = $('open'), status = $('status');

function b64(s) { const b = atob(s), u = new Uint8Array(b.length); for (let i = 0; i < b.length; i++) u[i] = b.charCodeAt(i); return u; }
function say(t, err) { status.textContent = t; status.className = 'status' + (err ? ' err' : ''); }

async function passwordKey(pass) {
    const raw = await crypto.subtle.importKey('raw', new TextEncoder().encode(pass), 'PBKDF2', false, ['deriveKey']);
    return crypto.subtle.deriveKey({ name: 'PBKDF2', salt: b64(SALT), iterations: ITER, hash: 'SHA-256' }, raw, { name: 'AES-GCM', length: 256 }, false, ['decrypt']);
}
function gcmOpen(key, buf) { return crypto.subtle.decrypt({ name: 'AES-GCM', iv: new Uint8Array(buf, 0, 12) }, key, new Uint8Array(buf, 12)); }

async function fetchWithProgress(url, onProgress) {
    const res = await fetch(url, { cache: 'force-cache' });
    if (!res.ok) throw new Error('missing');
    const total = +res.headers.get('content-length') || 0;
    if (!res.body || !res.body.getReader) return res.arrayBuffer();
    const reader = res.body.getReader(), chunks = []; let got = 0;
    for (;;) {
        const { done, value } = await reader.read();
        if (done) break;
        chunks.push(value); got += value.length;
        if (total) onProgress(Math.min(0.99, got / total));
    }
    const out = new Uint8Array(got); let o = 0;
    for (const c of chunks) { out.set(c, o); o += c.length; }
    return out.buffer;
}

async function unlock(pass) {
    btn.disabled = true; say('Opening the session…');
    try {
        if (!window.crypto || !crypto.subtle) throw new Error('This browser can’t open protected sessions. Use a current Chrome, Edge, Safari, Firefox or Meta Quest Browser.');
        const pk = await passwordKey(pass);
        let raw;
        try {
            const res = await fetch(BASE + KEY_FILE, { cache: 'no-cache' });
            if (!res.ok) throw new Error('missing');
            raw = await gcmOpen(pk, await res.arrayBuffer());
        } catch (e) {
            if (String(e && e.message) === 'missing') throw new Error('The preliminary video is not online yet. Please try again later.');
            say('That password didn’t work. Check it and try again.', true); btn.disabled = false; pw.select(); return;
        }
        try { sessionStorage.setItem(KEEP, pass); } catch (e) {}
        const ck = await crypto.subtle.importKey('raw', raw, { name: 'AES-GCM' }, false, ['decrypt']);
        const enc = await fetchWithProgress(BASE + VIDEO_FILE, (f) => say('Loading the video… ' + Math.round(f * 100) + '%'));
        say('Opening the video…');
        const data = await gcmOpen(ck, enc);
        start(URL.createObjectURL(new Blob([data], { type: 'video/mp4' })));
    } catch (e) {
        say(String(e && e.message || e), true); btn.disabled = false;
    }
}

form.addEventListener('submit', (e) => { e.preventDefault(); if (pw.value) unlock(pw.value); });
(async () => {
    // Until the locked video is uploaded, say so instead of asking for the password.
    let online = true;
    try { online = (await fetch(BASE + KEY_FILE, { method: 'HEAD', cache: 'no-cache' })).ok; } catch (e) {}
    if (!online) {
        form.querySelectorAll('label, .row').forEach((el) => { el.hidden = true; });
        $('access-lead').textContent = 'The preliminary AI-generated video is ready and will open here with the study password once it has been uploaded.';
        return;
    }
    let kept = null; try { kept = sessionStorage.getItem(KEEP); } catch (e) {}
    if (kept) unlock(kept); else pw.focus();
})();

// ---------------------------------------------------------------- player
function hemisphere(radius, cols, rows) {
    // Half-equirectangular mapping: u spans longitude −90°…+90° (left → right), v spans latitude −90°…+90° (bottom → top).
    const pos = [], uv = [], idx = [];
    for (let j = 0; j <= rows; j++) {
        const v = j / rows, lat = (v - 0.5) * Math.PI;
        for (let i = 0; i <= cols; i++) {
            const u = i / cols, lon = (u - 0.5) * Math.PI;
            pos.push(radius * Math.sin(lon) * Math.cos(lat), radius * Math.sin(lat), -radius * Math.cos(lon) * Math.cos(lat));
            uv.push(u, v);
        }
    }
    for (let j = 0; j < rows; j++) for (let i = 0; i < cols; i++) {
        const a = j * (cols + 1) + i, b = a + 1, c = a + cols + 1, d = c + 1;
        idx.push(a, c, b, b, c, d); // wound to face the centre
    }
    const g = new THREE.BufferGeometry();
    g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
    g.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2));
    g.setIndex(idx);
    return g;
}

function fmt(t) { t = Math.max(0, Math.floor(t || 0)); return Math.floor(t / 60) + ':' + String(t % 60).padStart(2, '0'); }

function start(src) {
    $('access').hidden = true;
    const stage = $('stage'); stage.hidden = false;
    const video = document.createElement('video');
    video.src = src; video.playsInline = true; video.setAttribute('playsinline', ''); video.preload = 'auto'; video.crossOrigin = 'anonymous';

    const renderer = new THREE.WebGLRenderer({ antialias: true });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    stage.insertBefore(renderer.domElement, stage.firstChild);
    const scene = new THREE.Scene(); scene.background = new THREE.Color(0x05080d);
    const camera = new THREE.PerspectiveCamera(DELIVERY === 'headset' ? 90 : 75, 1, 0.05, 100);
    scene.add(camera);
    const tex = new THREE.VideoTexture(video); tex.colorSpace = THREE.SRGBColorSpace; tex.minFilter = THREE.LinearFilter; tex.generateMipmaps = false;
    const dome = new THREE.Mesh(hemisphere(10, 96, 96), new THREE.MeshBasicMaterial({ map: tex, side: THREE.DoubleSide }));
    scene.add(dome);

    // Look around: drag on screen, or move the phone/tablet (magic window).
    let yaw = 0, pitch = 0, dragging = false, lx = 0, ly = 0, motion = null;
    const clampLook = () => { yaw = Math.max(-1.75, Math.min(1.75, yaw)); pitch = Math.max(-1.4, Math.min(1.4, pitch)); };
    const el = renderer.domElement;
    el.style.touchAction = 'none';
    el.addEventListener('pointerdown', (e) => { dragging = true; lx = e.clientX; ly = e.clientY; el.setPointerCapture(e.pointerId); });
    el.addEventListener('pointermove', (e) => {
        if (!dragging || motion) return;
        const k = (camera.fov * Math.PI / 180) / el.clientHeight;
        yaw += (e.clientX - lx) * k; pitch += (e.clientY - ly) * k; lx = e.clientX; ly = e.clientY; clampLook();
    });
    const endDrag = () => { dragging = false; };
    el.addEventListener('pointerup', endDrag); el.addEventListener('pointercancel', endDrag);
    window.addEventListener('keydown', (e) => {
        if (e.target && /INPUT|BUTTON/.test(e.target.tagName)) return;
        const s = 0.08;
        if (e.key === 'ArrowLeft') yaw += s; else if (e.key === 'ArrowRight') yaw -= s;
        else if (e.key === 'ArrowUp') pitch += s; else if (e.key === 'ArrowDown') pitch -= s;
        else if (e.key === ' ') { e.preventDefault(); toggle(); return; } else return;
        clampLook();
    });

    // Device orientation (phones and tablets).
    const zee = new THREE.Vector3(0, 0, 1), euler = new THREE.Euler(), q0 = new THREE.Quaternion(), q1 = new THREE.Quaternion(-Math.sqrt(0.5), 0, 0, Math.sqrt(0.5));
    let motionZero = null;
    function onOrient(e) { if (e.alpha == null) return; motion = e; }
    const motionBtn = $('motion');
    if (DELIVERY === 'screen' && 'DeviceOrientationEvent' in window && matchMedia('(pointer: coarse)').matches) {
        motionBtn.hidden = false;
        motionBtn.addEventListener('click', async () => {
            if (motion) { window.removeEventListener('deviceorientation', onOrient); motion = null; motionZero = null; motionBtn.setAttribute('aria-pressed', 'false'); return; }
            try { if (typeof DeviceOrientationEvent.requestPermission === 'function' && await DeviceOrientationEvent.requestPermission() !== 'granted') return; } catch (err) { return; }
            window.addEventListener('deviceorientation', onOrient); motionBtn.setAttribute('aria-pressed', 'true');
        });
    }
    function applyMotion() {
        const d = THREE.MathUtils.DEG2RAD, orient = (screen.orientation && screen.orientation.angle) || window.orientation || 0;
        euler.set(motion.beta * d, motion.alpha * d, -motion.gamma * d, 'YXZ');
        camera.quaternion.setFromEuler(euler); camera.quaternion.multiply(q1); camera.quaternion.multiply(q0.setFromAxisAngle(zee, -orient * d));
        if (!motionZero) { const f = new THREE.Vector3(0, 0, -1).applyQuaternion(camera.quaternion); motionZero = Math.atan2(-f.x, -f.z); }
        camera.quaternion.premultiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 1, 0), -motionZero));
    }

    // Controls.
    const playBtn = $('play'), restartBtn = $('restart'), muteBtn = $('mute'), timeEl = $('time'), bar = $('progress'), over = $('overlay'), overBtn = $('overlay-btn'), centreBtn = $('centre');
    function tryPlay() { video.play().catch(() => { playBtn.textContent = 'Play'; showOverlay('Play'); }); }
    function toggle() { if (video.paused || video.ended) tryPlay(); else video.pause(); }
    function showOverlay(label) { overBtn.textContent = label; over.hidden = false; }
    playBtn.addEventListener('click', toggle);
    restartBtn.addEventListener('click', () => { video.currentTime = 0; tryPlay(); });
    muteBtn.addEventListener('click', () => { video.muted = !video.muted; muteBtn.textContent = video.muted ? 'Sound on' : 'Mute'; });
    centreBtn.addEventListener('click', () => { yaw = 0; pitch = 0; motionZero = null; });
    overBtn.addEventListener('click', () => { over.hidden = true; if (video.ended) video.currentTime = 0; tryPlay(); });
    video.addEventListener('play', () => { playBtn.textContent = 'Pause'; over.hidden = true; });
    video.addEventListener('pause', () => { playBtn.textContent = 'Play'; });
    video.addEventListener('ended', () => showOverlay('Watch again'));
    video.addEventListener('timeupdate', () => { timeEl.textContent = fmt(video.currentTime) + ' / ' + fmt(video.duration); bar.style.width = (100 * video.currentTime / (video.duration || 1)) + '%'; });

    function resize() {
        const w = stage.clientWidth, h = stage.clientHeight;
        renderer.setSize(w, h, false); el.style.width = w + 'px'; el.style.height = h + 'px';
        camera.aspect = w / h; camera.updateProjectionMatrix();
    }
    window.addEventListener('resize', resize); resize();

    // Headset delivery (WebXR, immersive-vr). The dome is centred on the viewer's eyes and faces their forward direction.
    if (DELIVERY === 'headset') {
        renderer.xr.enabled = true;
        renderer.xr.setReferenceSpaceType('local');
        const vrBtn = $('vr');
        const ctrls = [renderer.xr.getController(0), renderer.xr.getController(1)];
        ctrls.forEach((c) => { c.addEventListener('select', toggle); scene.add(c); });
        if (navigator.xr) {
            navigator.xr.isSessionSupported('immersive-vr').then((ok) => {
                if (!ok) { vrBtn.textContent = 'VR not available in this browser'; vrBtn.disabled = true; return; }
                vrBtn.disabled = false; vrBtn.textContent = 'Enter VR';
                let session = null;
                vrBtn.addEventListener('click', async () => {
                    if (session) { session.end(); return; }
                    session = await navigator.xr.requestSession('immersive-vr', { optionalFeatures: ['local-floor'] });
                    session.addEventListener('end', () => { session = null; vrBtn.textContent = 'Enter VR'; });
                    await renderer.xr.setSession(session); vrBtn.textContent = 'Leave VR';
                    tryPlay();
                });
            });
        } else { vrBtn.textContent = 'VR not available in this browser'; vrBtn.disabled = true; }
    }

    renderer.setAnimationLoop(() => {
        if (!renderer.xr.isPresenting) {
            if (motion) applyMotion(); else camera.quaternion.setFromEuler(euler.set(pitch, yaw, 0, 'YXZ'));
        }
        renderer.render(scene, camera);
    });

    video.addEventListener('error', () => { say('This browser could not play the video. Try a current Chrome, Edge, Safari or Meta Quest Browser.', true); $('access').hidden = false; stage.hidden = true; });
    tryPlay();
}
